on:
  "inges_kattehjem":
    config:
      debug: false
      every: "0 8,10,12,14 * * *"
    tags:
    - Indekat
jobs:
  print:
    name: Print
    runs-on: ubuntu-latest
    steps:
      - name: Send to Discord
        uses: actionsflow/axios@main
        with:
          url: ${{ secrets.CATS_DISCORD_WEBHOOK }}
          method: POST
          body: |
            {
              "embeds": [{
                "title": ${{ toJSON(on.inges_kattehjem.outputs.name) }},
                "description": ${{ toJSON(on.inges_kattehjem.outputs.description) }},
                "url": ${{ toJSON(on.inges_kattehjem.outputs.link) }},
                "image": {
                  "url": ${{ toJSON(on.inges_kattehjem.outputs.imageUrl) }}
                }
              }]
            }
