on:
  "inges_kattehjem":
    config:
      debug: true
      every: "0 14 * * *"
    tags:
    - Indekat
jobs:
  print:
    name: Print
    runs-on: ubuntu-latest
    steps:
      - name: Print Outputs
        env:
          outputs: ${{ toJSON(on.inges_kattehjem.outputs) }}
        run: |
          echo Output: $outputs
      - name: Send to Discord
        uses: actionsflow/axios@main
        with:
          url: ${{ secrets.CATS_DISCORD_WEBHOOK }}
          method: POST
          body: |
            {
              "embeds": [{
                "title": ${{ toJSON(on.inges_kattehjem.outputs.name) }},
                "description": ${{ toJSON(on.inges_kattehjem.outputs.description) }},
                "url": ${{ toJSON(on.inges_kattehjem.outputs.link) }},
                "image": {
                  "url": ${{ toJSON(on.inges_kattehjem.outputs.imageUrl) }}
                }
              }]
            }